version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped

  rest:
    build:
      context: ./rest
      dockerfile: ../docker/rest/Dockerfile
    container_name: pgarden-rest
    ports:
      - "4000:3001"
      - "9229:9229"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: