version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: pgarden-web
    ports:
      - "3000:3000"
    restart: unless-stopped

  rest:
    build:
      context: ./rest
      dockerfile: ../docker/rest/Dockerfile
    env_file:
      - .env
    container_name: pgarden-rest
    ports:
      - "4000:3001"
      - "9229:9229"
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./rest:/app

  db:
    image: postgres:15
    container_name: pgarden-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: pgarden
      POSTGRES_PASSWORD: pgarden
      POSTGRES_DB: pgarden
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: